### ISSUE TITLE
run at ubuntu return error

### ISSUE THREAD

**Issue by vvahidkazemi** [giggls/osml10n#16]
Hi

I have 2 errors:

1: **Error return when I call make deb in lua_unac directory:**

root@****:/home/renderaccount/data/osml10n-master/lua_unac# make deb
dpkg-buildpackage -b -uc
dpkg-buildpackage: info: source package lua-unaccent
dpkg-buildpackage: info: source version 1.8-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Sven Geggus <[sven-debian@geggus.net](mailto:sven-debian@geggus.net)>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build .
 debian/rules clean
make[1]: Entering directory '/home/renderaccount/data/osml10n-master/lua_unac'
dh clean
   dh_auto_clean
    make -j16 clean
make[2]: Entering directory '/home/renderaccount/data/osml10n-master/lua_unac'
rm -f unaccent.so
make[2]: Leaving directory '/home/renderaccount/data/osml10n-master/lua_unac'
   dh_clean
make[1]: Leaving directory '/home/renderaccount/data/osml10n-master/lua_unac'
 debian/rules build
make[1]: Entering directory '/home/renderaccount/data/osml10n-master/lua_unac'
dh build
   dh_update_autotools_config
   dh_autoreconf
   dh_auto_configure
   dh_auto_build
    make -j16 "INSTALL=install --strip-program=true"
make[2]: Entering directory '/home/renderaccount/data/osml10n-master/lua_unac'
gcc -Wall -shared -fPIC -o unaccent.so -I/usr/include/lua5.3 -llua5.3 -Wl,--no-as-needed -lunac lua_unac.c
lua_unac.c:14:10: fatal error: lua.h: No such file or directory
   14 | #include <lua.h>
      |          ^~~~~~~
compilation terminated.
make[2]: *** [Makefile:7: unaccent.so] Error 1
make[2]: Leaving directory '/home/renderaccount/data/osml10n-master/lua_unac'
dh_auto_build: error: make -j16 "INSTALL=install --strip-program=true" returned exit code 2
make[1]: *** [debian/rules:18: build] Error 2
make[1]: Leaving directory '/home/renderaccount/data/osml10n-master/lua_unac'
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
make: *** [Makefile:13: deb] Error 2
root@****:/home/renderaccount/data/osml10n-master/lua_unac# make test
make: *** No rule to make target 'test'.  Stop.

2: **Error when i run osm2pgsql** 

renderaccount@****:~$ osm2pgsql -G -O -d gis -S ~/data/osml10n-master/openstreetmap-carto-hstore-only-l10n.lua asia-latest.osm.pbf
osm2pgsql version 1.2.1 (64 bit id space)

Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=800MB, maxblocks=12800*65536, allocation method=3
DB writer thread failed due to ERROR: Connection to database failed: FATAL:  database "renderaccount" does not exist

**Comment by giggls** [comment]
Did you actually follow the instructions in INSTALL.md?

Why am I asking this?

Well because your first "issue" looks like you did not install ``liblua5.3-dev``.
I have now added this dependency to debian/rules. This way the build should not even try to start.

Regarding you second "issue":
As I already said: Please RTFM!
osm2pgsql version 1.2.1 is way too old for this code.

This said. I can not resolve "issues" out of the blue air. You did not even tell me which Version of Ubuntu you are trying to do this.

**Comment by vvahidkazemi** [comment]
Hi

thank you for your patience...
I'm running Ubuntu 20.04.4 LTS.
