### ISSUE TITLE
undefined symbol: unac_string

### ISSUE THREAD

**Issue by Dexolite** [giggls/osml10n#2]
On ubuntu:20.04
Following your instructions, added the dependencies, lua_unac makes ok (installed), however when trying to make lua_osml10, getting the error undefined symbol: unac_string. 

Additional related info: libunac1-dev is already the newest version (1.8.0-8)
lua5.3/focal,now 5.3.3-1.1ubuntu2 amd64 [installed]

Can you please provide some insight on what I'm doing wrong here ?

Here is the  output of "cd lua_osml10 && make deb" :

`make[2]: Entering directory '/home/renderer/src/osml10n/lua_osml10'
./tests/runtests.lua
/usr/bin/lua: error loading module 'unaccent' from file '/usr/lib/x86_64-linux-gnu/lua/5.3/unaccent.so':
	/usr/lib/x86_64-linux-gnu/lua/5.3/unaccent.so: undefined symbol: unac_string
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	/usr/share/lua/5.3/osml10n/get_localized_name_from_tags.lua:1: in main chunk
	[C]: in function 'require'
	/usr/share/lua/5.3/osml10n/init.lua:4: in local 'import'
	/usr/share/lua/5.3/osml10n/init.lua:14: in main chunk
	[C]: in function 'require'
	./tests/runtests.lua:6: in main chunk
	[C]: in ?
make[2]: *** [Makefile:15: test] Error 1
make[2]: Leaving directory '/home/renderer/src/osml10n/lua_osml10'
dh_auto_test: error: make -j8 test returned exit code 2
make[1]: *** [debian/rules:18: build] Error 2
make[1]: Leaving directory '/home/renderer/src/osml10n/lua_osml10'
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
make: *** [Makefile:18: deb] Error 2`

**Comment by giggls** [comment]
First of all? Are you aware of the fact that you are trying to install experimental code which is not yet in use anywhere?

I wrote an explanation why this code is not yet in production in my blog https://blog.geggus.net/2020/09/why-development-of-german-osm-carto-style-is-currently-stuck/.

So let me first ask what you intend to do?

Because you might well be better off using the legacy code from https://github.com/giggls/mapnik-german-l10n for now.

BTW I get the same error on Debian 11 here so feel free to fix it and send a patch :)

**Comment by Dexolite** [comment]
Thanks for the response. I'm trying to get the name:en with the local names, to no avail.
The mapnik-german is having trouble compiling on ubuntu for me. Also the COALESCE(tags->'name:en', name, '') AS name , It returning Posgis error no column tags ?!

Why is it so hard to get english labels :( Am I missing something

**Comment by giggls** [comment]
Well, if it tells your there is no column "tags" in your database this is likely the case.

Did you have a look at 
https://github.com/giggls/openstreetmap-carto-de/blob/master/INSTALL-de.md?
