### ISSUE TITLE
mml file 

### ISSUE THREAD

**Issue by aravgh** [giggls/osml10n#20]
Hello,

Sorry I am not expert in OSM can you please help me understand something abut next steps?
If I understand after packages installation and importing DB I need some custom mml file to build XML stylesheet? because with standard project.mml file from openstreetmap-carto I was not able to make renderd work properly...
I am using debian11, your code is installed and listening on port 8033. 
make test  result: 87 test passed, 0 tests filed.
OSM file successfully imported. Everything is done as mentioned in your installation guide.

Thanks in advance!

**Comment by giggls** [comment]
Frankly, What do you expect?
Maybe start from here: https://github.com/giggls/openstreetmap-carto-de
