### ISSUE TITLE
Error when running make test

### ISSUE THREAD

**Issue by dvigh8** [giggls/osml10n#24]
I get the following error when running make test on ubuntu 22.04

cd lua_osml10/tests/ && ./runtests.lua
/usr/bin/lua: ./osml10n/geo_transcript.lua:10: Can not connect to server 127.0.0.1:8033. Is geo-transcript-srv.py running?
stack traceback:
	[C]: in function 'error'
	./osml10n/geo_transcript.lua:10: in main chunk
	[C]: in function 'require'
	./osml10n/init.lua:4: in local 'import'
	./osml10n/init.lua:13: in main chunk
	[C]: in function 'require'
	./osml10n.lua:1: in main chunk
	[C]: in function 'require'
	./runtests.lua:6: in main chunk
	[C]: in ?
make: *** [Makefile:31: test] Error 1

**Comment by giggls** [comment]
Citing the error message:
"Is geo-transcript-srv.py running?"

**Comment by dvigh8** [comment]
It wasn't running. Turns out ubuntu doesn't let it bind to port 8033 when local bind address is localhost. Runs with 127.0.0.1
The updated install instructions are easier to understand as well, Thanks.

**Comment by dvigh8** [comment]
One other problem I had when starting the server was with tltk was that sklearn was not installed. Not sure how that wasn't installed but I did have to do a pip install scikit-learn to get it to work
