### ISSUE TITLE
transcription-daemon does not auto-start after debian packages are installed.

### ISSUE THREAD

**Issue by comiquita** [giggls/osml10n#25]
Hi there,

On ubuntu 22.04, with the correct python dependencies as per install manual.

After I do the following:
`dpkg -i lua-unaccent_*.deb
dpkg -i ../osml10n_*_all.deb`

I obtain

`
sudo dpkg -i /home/alexander/src/osml10n_1.0.1_all.deb               
Selecting previously unselected package osml10n.
dpkg: warning: files list file for package 'osml10n-build-deps' missing; assuming package has no files currently installed
(Reading database ... 347404 files and directories currently installed.)
Preparing to unpack .../src/osml10n_1.0.1_all.deb ...
Unpacking osml10n (1.0.1) ...
Setting up osml10n (1.0.1) ...
Could not execute systemctl:  at /usr/bin/deb-systemd-invoke line 142.
`

I've been researching about that message with no luck. 

However, runnning the following command works:
`/usr/bin/geo-transcript-srv.py -s -g /usr/share/osml10n/boundaries`

And when I open another terminal, and run make test, it all works fine and no error from the server.

lastly, when I open another terminal and run:

`
$ systemctl status osml10n.service
× osml10n.service - OSM l10n transcription server
     Loaded: loaded (/lib/systemd/system/osml10n.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2023-03-18 16:23:31 EDT; 8min ago
    Process: 228488 ExecStart=/usr/bin/geo-transcript-srv.py -s -g /usr/share/osml10n/boundaries (code=exited, status=1/FAILURE)
   Main PID: 228488 (code=exited, status=1/FAILURE)
        CPU: 88ms

Mar 18 16:23:31 127.0.0.1localhost systemd[1]: osml10n.service: Scheduled restart job, restart counter is at 5.
Mar 18 16:23:31 127.0.0.1localhost systemd[1]: Stopped OSM l10n transcription server.
Mar 18 16:23:31 127.0.0.1localhost systemd[1]: osml10n.service: Start request repeated too quickly.
Mar 18 16:23:31 127.0.0.1localhost systemd[1]: osml10n.service: Failed with result 'exit-code'.
Mar 18 16:23:31 127.0.0.1localhost systemd[1]: Failed to start OSM l10n transcription server.
`

**Comment by giggls** [comment]
I can not reproduce your problems with dpkg -i in my Ubuntu 22.04 chroot

For technical reasons I can not check autostart in a chroot.

```
root@ceres:~/osml10n# dpkg -i ../osml10n_*_all.deb
Selecting previously unselected package osml10n.
(Reading database ... 28338 files and directories currently installed.)
Preparing to unpack ../osml10n_1.0.1_all.deb ...
Unpacking osml10n (1.0.1) ...
Setting up osml10n (1.0.1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/osml10n.service -> /lib/systemd/system/osml10n.service.
```

**Comment by Bonjour123** [comment]
Same error here: 
Could not execute systemctl:  at /usr/bin/deb-systemd-invoke line 142.


When trying to restart:

```

 sudo systemctl restart osml10n.service

Job for osml10n.service failed because the control process exited with error code.
See "systemctl status osml10n.service" and "journalctl -xeu osml10n.service" for details.

```

**Comment by giggls** [comment]
As I already wrote. I can not check autostart in the chroot I set up while trying to reproduce this problem. Does ``journalctl -u osml10n`` tell something useful?

**Comment by giggls** [comment]
Daemon is now installed manually.
