### ISSUE TITLE
lake of osml10n.control

### ISSUE THREAD

**Issue by kftseng** [giggls/osml10n#26]
CREATE EXTENSION osml10n CASCADE;
ERROR:  extension "osml10n" is not available
DETAIL:  Could not open extension control file "/usr/share/postgresql/15/extension/osml10n.control": No such file or directory.
HINT:  The extension must first be installed on the system where PostgreSQL is running.

**Comment by giggls** [comment]
Why do you even think that there should be an PortgreSQL extension.
If you want to use the old deprecated code which does use an PortgreSQL extension look at:
https://github.com/giggls/mapnik-german-l10n
