### ISSUE TITLE
add osml10n as extention to postgreSQL

### ISSUE THREAD

**Issue by maminarghavani** [giggls/osml10n#28]
hi,
is there any way to add osml10n as an extension to PostgreSQL?
sorry if my question is irrelevant.

**Comment by giggls** [comment]
Did you read the history part of the README? The sole purpose of the new code is to no longer do this inside PostgreSQL. Why would you want to do this?

**Comment by maminarghavani** [comment]
> Did you read the history part of the README? The sole purpose of the new code is to no longer do this inside PostgreSQL. Why would you want to do this?

ok thanks
