### ISSUE TITLE
make deb error 

### ISSUE THREAD

**Issue by HumeyraTEZCAN** [giggls/osml10n#30]
Hi everyone, I clone repository and run sudo mk-build-deps -i debian/control then when I run make deb I get following errors. I use postggresql16. Why does this happens, can someone help?
![screenshot](https://github.com/giggls/osml10n/assets/44144939/a21a3a2f-8774-4172-8bdd-59a657f81df3)

**Comment by giggls** [comment]
This report is related to the **deprecated** legacy code (mapnik-german-l10n repository) which is no longer maintained.
