### ISSUE TITLE
Unable to get any output

### ISSUE THREAD

**Issue by nbkhwjm** [giggls/osml10n#32]
I'm sure I have a fundamental mis-understanding of how this is supposed to work but i'm not getting any output.    If you want me to post elsewhere let me know..

**Current process.**

- Ive built a new server Ubuntu 22.04 (only chose this because its easy, i'm happy to build a Debian X, for troubleshooting)
- used the following tutorial to get a working OSM server --> https://www.linuxbabe.com/linux-server/osm-openstreetmap-tile-server-ubuntu-22-04
- I'm able to import planet no problem, but upon a rebuild I'm using a very small pbf.. pitcairns-islands-latest.pbf to verify the whole system is working.

`./osm2pgsql --slim -d gis --hstore --multi-geometry --number-processes 32 --tag-transform-script /home/osm/openstreetmap-carto/openstreetmap-carto.lua --style /home/osm/openstreetmap-carto/openstreetmap-carto.style -C 132000 ./pitcairn-islands-latest.osm.pbf`

- I then attempt to import a small pbf using yours with a small japanese island skikoku pbf like:
`./osm2pgsql -G -O flex -d gis -S /osml10n/openstreetmap-carto-hstore-only-l10n.lua ./shikoku-latest.osm.pbf
`
- I stop the render daemon
`systemctl stop renderd`

- clear the tiles directory
`rm -rf  /var/cache/renderd/tiles/default/*`

- clear the browser cache

- restart the render daemon
`systemctl start renderd`

- use render_list to force tile creation...
`render_list -m default -a -z 3 -Z 19 --num-threads=40`

When I check the map, the only tiles that are created are the previous ones from pitcairns island.

**Comment by nbkhwjm** [comment]
an update..
I have a script that resets the DB (drop, reinstall extensions, set perms, reload external etc).  Then i use osm2pgsql to load the data.


This is the command that i'm using when loading with osml10n:
`sudo -u postgres /osm2/osm2pgsql/build/osm2pgsql --verbose --output=flex --slim --database=gis --hstore --multi-geometry --number-processes=32 --style=/osml10n/openstreetmap-carto-hstore-only-l10n.lua --cache=150000 /osm2/osm2pgsql/build/shikoku-latest.osm.pbf`

When i use this, i get an error in syslog.
`renderd[82858]: ** (process:82858): ERROR **: 03:06:34.307: An error occurred while loading the map layer 'default': Postgis Plugin: ERROR:  relation "planet_osm_polygon" does not exist
`

if i use this command, it works perfectly, but no flex and with local labels.
`sudo -u postgres /osm2/osm2pgsql/build/osm2pgsql --slim --database=gis --drop --flat-nodes=/home/osm/nodes.cache --hstore --multi-geometry --number-processes=32 --tag-transform-script=/home/osm/openstreetmap-carto/openstreetmap-carto.lua --style=/home/osm/openstreetmap-carto/openstreetmap-carto.style --cache=150000 /osm2/osm2pgsql/build/shikoku-latest.osm.pbf`

**Comment by nbkhwjm** [comment]
i can see that the relations do not exist, so i looked in the lua file and can see that the local prefix is "planet_osm_hstore" so i changed that to "planet_osm", but thats caused some other column errors.  So i need to dig into that more.

do i need a custom style for renderd to match the osm2pgsql flex output lua?

**Comment by giggls** [comment]
Frankly your issue is off-topic here.  This is about localisation and not about how to set up a tile-server or even using some kind of carto style. Thus I will give you a few hints and will then close this. 

1. For how to set up a localized Tile-Server refer to the Manual in German Carto style: https://github.com/giggls/openstreetmap-carto-de/blob/master/INSTALL-de.md
2. For rendering tests use the script https://github.com/giggls/openstreetmap-carto-de/blob/master/scripts/render_single_tile.py I am providing in my style repository. Setting up mod-tile and renderd/tirex is then yout next step if rendering using this scripts works.
3. My style uses views which are called like the tables in the upstream style to maintain compatibility (see https://github.com/giggls/openstreetmap-carto-de/blob/master/INSTALL-de.md)
4. If you do not like German Map colors use upstream+l10n branch.

**Comment by nbkhwjm** [comment]
Understood, thanks for the hints.

**Comment by nbkhwjm** [comment]
@giggls your hints were excellent, I was able to get this to work. thank you for your support.. (and tolerance) :-)

![image](https://github.com/giggls/osml10n/assets/10811381/539436d3-defd-42e7-9764-2d76edaff565)

for anyone else who stumbles upon this thread..  here are the important bits


**in osml10n**
- make sure "make test" gives no errors.. this bit is the "magic" that makes this possible..
- import a small pbf using his recommended osm2pgsql command


**in openstreetmap-carto-de**
- create the views with ./views_osmde/apply-views.sh osm (note that the osm is the dbname, mine was "gis" so you need to change that
- generate osm-de.xml 
- i had to change the dbname parameter in osm-de.xml from osm to gis in osm-de.xml with sed -i 's/\[osm\]/\[gis\]/g' ./osm-de.xml.  im sure theres a better way to do this.
- set osm-de.xml as the XML value in renderd "XML=/openstreetmap-carto-de/osm-de.xml"
- restart renderd

**Comment by giggls** [comment]
Yes for some reason I found gis a strange name for an osm database. Just replace the dbname in project.mml and recompile osm-de.xml using make. This will require a working carto command.
