### ISSUE TITLE
Add GitHub description

### ISSUE THREAD

**Issue by otbutz** [giggls/osml10n#33]
Not really an issue, just to satisfy my OCD :wink: 

![image](https://github.com/giggls/osml10n/assets/22315436/3450be96-ced7-49fb-8cc9-f640ef47b8b3)

Maybe the text from the release notes?

`Localization functions for Openstreetmap`

**Comment by giggls** [comment]
Well as there is no Website. README.md is all I currently have.
Added a link to https://tile.openstreetmap.de

**Comment by otbutz** [comment]
I would also add the [openstreetmap](https://github.com/topics/openstreetmap) topic for better discoverability.

**Comment by giggls** [comment]
I'm also going to restructure the README a little bit. To start from a descrition what this is all about.
