### ISSUE TITLE
Possibility to run without a daemon

### ISSUE THREAD

**Issue by mkesper** [giggls/osml10n#36]
From the description it seems the tool would also be runnable without a daemon by calling `osm2pgsql -G -s -O flex -d osm -S openstreetmap-carto-hstore-only-l10n.lua planet.osm.pbf`

Is that the case? If not, it should probably be mentioned in that paragraph explicitly. If it is, a Makefile target installing just enough to do so would be nice. E.g. in a container you probably don't want to run systemd.

**Comment by giggls** [comment]
Why did you get this impression?
Which part of this sentence is difficult to understand?

"Unfortunately however the most FOSS transcription libraries are written in Python not Lua and we want to use them. Thus we decided to make a daemon doing Latin transcription written in this programming language."

**Comment by mkesper** [comment]
If you just read https://github.com/giggls/osml10n/blob/master/INSTALL.md#rendering-a-l10n-version-of-openstreetmap-carto you could get that impression. I know that installation is described above, probably hoped to have a shortcut.
Feel free to close...

**Comment by giggls** [comment]
The daemon is needed because transcription is solely done in python. So if you do not run the daemon transcription will work.

**Comment by giggls** [comment]
Probably I should add a link to the German tileserver ansible playbook.
https://github.com/fossgis-routing-server/ansible_openstreetmap.de
