### ISSUE TITLE
osml10n.service is not starting

### ISSUE THREAD

**Issue by sdranju** [giggls/osml10n#41]
Service is not starting due to missing 'pkg_resources' module (Ubuntu 24.04). Adding 'setuptools' in the 'setup.py' fixed the issue.
    ...
    install_requires=[
        "setuptools",
        "scipy",
        ...
        "pandas"
    ]

-- Reinstall the service after the modification in 'setup.py'
# sudo make install-daemon

-- Error
# journalctl -u osml10n.service
Sep 19 12:28:00 gis01 systemd[1]: osml10n.service: Scheduled restart job, restart counter is at 1.
Sep 19 12:28:00 gis01 systemd[1]: Starting osml10n.service - OSM l10n transcription server...
Sep 19 12:28:00 gis01 geo-transcript-srv.py[11144]: Traceback (most recent call last):
Sep 19 12:28:00 gis01 geo-transcript-srv.py[11144]:   File "/usr/local/osml10n/bin/geo-transcript-srv.py", line 13, in <module>
Sep 19 12:28:00 gis01 geo-transcript-srv.py[11144]:     import pkg_resources
Sep 19 12:28:00 gis01 geo-transcript-srv.py[11144]: ModuleNotFoundError: No module named 'pkg_resources'
Sep 19 12:28:00 gis01 systemd[1]: osml10n.service: Main process exited, code=exited, status=1/FAILURE

**Comment by giggls** [comment]
As I do not use Ubuntu myself this might well not work on Ubuntu 24.04 in its current stage.
I just checked that adding the "setuptools" dependency does not seem to make trouble in Debian 12 thus it is probably best to add it and close this issue.
Any Objections?

**Comment by sdranju** [comment]
Great.
