### ISSUE TITLE
openmaptiles requires pgsql extension for osml10n

### ISSUE THREAD

**Issue by sdranju** [giggls/osml10n#42]
I'm building a new vector tiles server using openmaptiles, Ubuntu 24.04 and PgSQL 16. But I want to use this tool instead of 'mapnik-german-l10n'. The problem is, openmaptiles heavily dependent on osml10n pgsql extension and sql import fails with command 'make import-sql'. Help me to have a workaround.

Error:
psql:/usr/src/app/sql/zzz_language.sql:74: ERROR:  function osml10n_get_name_without_brackets_from_tags(hstore, unknown, geometry) does not exist
LINE 9:       NULLIF(osml10n_get_name_without_brackets_from_tags(tag...
                     ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Time: 0.607 ms
make: *** [Makefile:453: import-sql] Error 3

**Comment by giggls** [comment]
There is no Postgresql Extension anymore because it would no longer make sense.
The new approach does l10n while importing data. See https://github.com/giggls/osml10n/blob/master/README.md for details.
