### ISSUE TITLE
Failed to execute Lua function 'osm2pgsql.process_relation'

### ISSUE THREAD

**Issue by luzhskij** [giggls/osml10n#44]
Hello!
The software was installed according to the instructions, all tests are OK.
When trying to process a file, this error occurs. Any ideas what could be wrong?
System: Ubuntu 22.04.5 LTS, osm2pgsql version 1.6.0.
1) Created a clean database, added hstore and postgis extensions.
2) In file openstreetmap-carto-hstore-only-l10n.lua changed language:
```
-- Target language
local lang = 'en'
```
3) Command: `osm2pgsql -G -s -O flex --database armenia -U "postgres" -W -H "localhost" -S openstreetmap-carto-hstore-only-l10n.lua /home/user/Downloads/armenia-latest.osm.pbf`
4) Have error:
```
~  Database version: 14.13 (Ubuntu 14.13-0ubuntu0.22.04.1)
~  PostGIS version: 3.2
Processing: Node(7647k 955.9k/s) Way(674k 48.14k/s) Relation(10 10.0/s)
~  ERROR: Failed to execute Lua function 'osm2pgsql.process_relation': /usr/share/lua/5.3/osml10n/geo_transcript.lua:23: Error in 'get_bbox': The function get_bbox() can only be called from process_node() or process_way().

stack traceback:
	[C]: in local 'bbox'
	/usr/share/lua/5.3/osml10n/geo_transcript.lua:23: in function 'osml10n.geo_transcript.geo_transcript'
	/usr/share/lua/5.3/osml10n/get_localized_name_from_tags.lua:321: in function 'osml10n.get_localized_name_from_tags.get_names_from_tags'
	openstreetmap-carto-hstore-only-l10n.lua:592: in function <openstreetmap-carto-hstore-only-l10n.lua:562>.
```

**Comment by giggls** [comment]
Citing INSTALL.md:
This will require osm2pgsql version 1.7.0 or newer!

**Comment by luzhskij** [comment]
> Citing INSTALL.md: This will require osm2pgsql version 1.7.0 or newer!

I'm sorry! I didn't notice the elephant in the room.
